USER-SUPPLIED VALUES:
USER-SUPPLIED VALUES: null
global:
  storageClass: local-path
mariadb:
  primary:
    nodeSelector:
      kubernetes.io/role: worker-for-website1
metrics:
  enabled: true
nodeSelector:
  kubernetes.io/role: worker-for-website1
service:
  type: NodePort
resources:
  requests:
    cpu: "4"
    memory: "8Gi"
  limits:
    cpu: "4"
    memory: "8Gi"
replicaCount: 1
extraVolumeMounts:
  - name: php-ini
    mountPath: /opt/bitnami/php/etc/conf.d

extraVolumes:
  - name: php-ini
    configMap:
      name: php-ini
customPostInitScripts:
  wp_memory_limit.sh: |
    sed -i "/.*That's all, stop editing! Happy publishing.*/i define('WP_MEMORY_LIMIT', '512M');" /opt/bitnami/wordpress/wp-config.php
# autoscaling:
#   enabled: true
#   minReplicas: 1
#   maxReplicas: 4
