USER-SUPPLIED VALUES:
USER-SUPPLIED VALUES: null
global:
  storageClass: local-path
mariadb:
  primary:
    nodeSelector:
      kubernetes.io/role: worker-for-website
metrics:
  enabled: true
nodeSelector:
  kubernetes.io/role: worker-for-website
service:
  type: NodePort
resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"
replicaCount: 2
# https://help.servmask.com/2018/10/27/how-to-increase-maximum-upload-file-size-in-wordpress/
wordpressExtraConfigContent: |
  @ini_set( 'upload_max_filesize', '1G' );
  @ini_set( 'post_max_size', '1G' );
  @ini_set( 'memory_limit', '1G' );
  @ini_set( 'max_execution_time', '0' );
  @ini_set( 'max_input_time', '0' );

# autoscaling:
#   enabled: true
#   minReplicas: 1
#   maxReplicas: 4
